---
title: "Gjenstående cacher for snohan"
knit: (function(input_file, encoding){
  rmarkdown::render(input_file, encoding=encoding, output_file = 'docs/index.html')})
output: 
  html_document:
    css: "geofun.css"
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
base::Sys.setlocale(locale = "nb.utf8")
library(tidyverse)
library(sf)
library(lwgeom)
library(leaflet)
library(knitr)
library(flextable)
library(scales)
library(DT)

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  cache = FALSE
)

# TODO: make a prep script
today_as_date <- lubridate::today()
```

```{r functions}
# To calculate distance from 
# 1. home location N 63° 23.567′ E 10° 25.026′
my_pois <- 
  tibble::tibble(
    place_name = c("home"),
    lon = c(10.41710),
    lat = c(63.39278)
  ) %>% 
  sf::st_as_sf(
    coords = c("lon", "lat"), 
    crs = 4326
  )

#pq_layers <- sf::st_layers(pocket_query)

# TODO: differentiate bewtween pq and downloaded list: The former has DT info, the latter doesn't!
#pq_gpx_file <- "gclists/hamar.gpx"

read_pq_data <- function(pq_gpx_file) {
  
  pq_data <- 
    sf::st_read(
      pq_gpx_file, 
      layer = "waypoints", 
      quiet = TRUE
    ) %>%
    dplyr::select(
      gc_code = name, 
      title = urlname,
      url,
      desc, 
      placed_on = time, 
      type
    ) %>%
    dplyr::filter(
      stringr::str_detect(gc_code, "^GC")
    ) %>%
    tidyr::separate(
      desc, 
      c("name_dup", "rest"), 
      sep = " by "
    ) %>%
    tidyr::separate(
      rest, 
      c("co", "dt"), 
      sep = "\\("
    ) %>%
    tidyr::separate(
      dt, 
      c("difficulty", "terrain"), 
      sep = "/"
    ) %>%
    dplyr::mutate(
      title = stringr::str_trim(title),
      co = stringr::str_replace(co, ", Traditional Cache", ""),
      co = stringr::str_replace(co, ", Virtual Cache", ""),
      co = stringr::str_replace(co, ", Earthcache", ""),
      difficulty = as.numeric(difficulty),
      terrain = as.numeric(stringr::str_sub(terrain, 1, -2)),
      placed_on = lubridate::as_date(placed_on),
      year = lubridate::year(placed_on),
      month = lubridate::month(placed_on),
      day = lubridate::mday(placed_on),
      type = stringr::str_sub(type, 10, -1),
      type = dplyr::case_when(
        stringr::str_starts(title, "Challenge:") ~ "Challenge Cache",
        TRUE ~ type
      ),
      distance_from_home = 
        sf::st_distance(geometry, my_pois$geometry[1]) %>%
                    round()
    ) %>%
    dplyr::select(
      type, 
      gc_code, 
      title,
      url,
      co, 
      difficulty, 
      terrain,
      placed_on, 
      year, 
      month, 
      day,
      distance_from_home
    )
  }
```


```{r read}
#pq_data <- read_pq_data("gclists/to_find_trd.gpx")
  
trondheim <- read_pq_data("gclists/trondheim.gpx") %>% 
  dplyr::mutate(Kommune = "Trondheim")

rendalen <- read_pq_data("gclists/rendalen.gpx") %>% 
  dplyr::mutate(Kommune = "Rendalen")

hamar <- read_pq_data("gclists/hamar.gpx") %>% 
  dplyr::mutate(Kommune = "Hamar")

missing_finds <- 
  dplyr::bind_rows(
    trondheim,
    rendalen,
    hamar
  ) %>% 
  sf::st_drop_geometry()

missing_finds_per_year <- missing_finds %>% 
  dplyr::group_by(year, Kommune) %>% 
  dplyr::summarise(antall = n(), .groups = "drop") %>% 
  tidyr::complete(year = 2001:2022, nesting(Kommune), fill = list(antall = 0)) %>% 
  tidyr::pivot_wider(names_from = Kommune, values_from = antall)
  
missing_finds_total <- missing_finds %>% 
  dplyr::group_by(Kommune) %>% 
  dplyr::summarise(antall = n(), .groups = "drop") %>% 
  tidyr::pivot_wider(names_from = Kommune, values_from = antall)

missing_finds_total_per_type <- missing_finds %>% 
  dplyr::group_by(Kommune, type) %>% 
  dplyr::summarise(antall = n(), .groups = "drop") %>% 
  tidyr::pivot_wider(names_from = Kommune, values_from = antall) %>% 
  dplyr::arrange(type) %>% 
  dplyr::rename(Type = type)

# TODO: ratio of solved mysteries
all_ready <- read_pq_data("gclists/all_ready.gpx")

solved_mysteries <- all_ready %>% 
  dplyr::select(gc_code) %>% 
  dplyr::mutate(solved = TRUE)

missing_finds_mysteries <- 
  missing_finds %>% 
  dplyr::filter(
    type == "Unknown Cache"
  ) %>% 
  dplyr::left_join(
    solved_mysteries, 
    by = "gc_code"
  ) %>% 
  dplyr::mutate(
    solved = dplyr::if_else(is.na(solved), FALSE, TRUE)
  )

missing_mysteries_summarized <- 
  missing_finds_mysteries %>% 
  dplyr::group_by(
    Kommune, 
    solved
  ) %>% 
  dplyr::summarise(
    antall = n(),
    .groups = "drop"
  ) %>% 
  tidyr::complete(
    solved = c(TRUE, FALSE), 
    nesting(Kommune), 
    fill = list(antall = 0)
  ) %>% 
  tidyr::pivot_wider(
    names_from = Kommune, 
    values_from = antall
  )
```

Sist oppdatert `r lubridate::mday(today_as_date)`. `r lubridate::month(today_as_date, abbr = F, label = T)` `r lubridate::year(today_as_date)`.

## Antall manglende cachefunn per utleggsår

```{r table_per_year}
missing_finds_per_year %>% 
  flextable::flextable() %>% 
  colformat_double(j = 1, big.mark = "", digits = 0) %>% 
  set_header_labels(year = "Utleggsår") %>% 
  theme_booktabs(bold_header = TRUE) %>% 
  bg(bg = "#c0c0c0", part = "header") %>% 
  bg(i = ~ Hamar == 0, j = 2, bg = "#099900", part = "body") %>% 
  bg(i = ~ Rendalen == 0, j = 3, bg = "#099900", part = "body") %>% 
  bg(i = ~ Trondheim == 0, j = 4, bg = "#099900", part = "body")

# TODO: color year if all are 0
```


## Antall manglende totalt

```{r table_total}
missing_finds_total %>% 
  flextable::flextable() %>% 
  theme_booktabs(bold_header = TRUE) %>% 
  bg(bg = "#c0c0c0", part = "header")
```


## Antall manglende per type

```{r table_total_type}
missing_finds_total_per_type %>% 
  flextable::flextable() %>% 
  theme_booktabs(bold_header = TRUE) %>% 
  bg(bg = "#c0c0c0", part = "header") %>% 
  set_table_properties(width = .47, 
                       layout = "autofit")
```


## Antall løste mysterier

```{r mysteries}
missing_mysteries_summarized %>% 
  flextable::flextable() %>% 
  theme_booktabs(bold_header = TRUE) %>% 
  bg(bg = "#c0c0c0", part = "header") %>% 
  set_table_properties(width = .47, 
                       layout = "autofit")
```


## Uløste mysterier

```{r unsolved}
missing_finds_mysteries %>%
  dplyr::filter(
    solved == FALSE
  ) %>% 
  dplyr::mutate(
    title_url = 
      paste0(
        "<a href=\"",
        url,
        "\" target=\"_blank\">",
        title,
        "</a>"
      )
  ) %>% 
  dplyr::select(
    Tittel = title_url,
    CO = co,
    Utlagt = year,
    Kommune
  ) %>% 
  DT::datatable(
    filter = "top",
    options = list(
      dom = "Blfrtip",
      pageLength = 25,
      lengthMenu = c(25, 50, 100),
      autoWidth = TRUE),
    escape = FALSE
  )
```




